### ISSUE TITLE
RuntimeError: vmap: called random operation while in randomness error mode. 

### ISSUE THREAD

**Issue by xiangmind** [TuringQ/deepquantum#25]
**ENV:**
![image](https://github.com/user-attachments/assets/52a3788d-850f-46e4-9fc9-354484b0a0b5)

**BUG:**

![image](https://github.com/user-attachments/assets/08e2989d-bb89-41d0-beda-b10170f96075)

![image](https://github.com/user-attachments/assets/1c6f8ae3-3ca4-4704-89de-7607dd246972)

A colab notebook to reproduce this bug:
https://colab.research.google.com/drive/1EwjCLUghzJrMfNw8JmHu95cKEKf-sqMR?usp=sharing

if comment this line, then bug gone
`self.circuit.latent(wires=list(range(self.num_qubits))) `

I think `torch.vmap` and `LatentGate` is not compatible.

**Comment by sansiro77** [comment]
Everything is fine in my local environment with CPU-version PyTorch 2.2.2. We need more detailed tests (GPU or PyTorch 2.3.1) to reproduce and debug locally.

**Comment by Jooyuza** [comment]
Got the same bug in my local environment with GPU version PyTorch 2.3.1.

However, everything turns well with GPU version Pytorch 2.2.2+cuda12.1, as follows:
![image](https://github.com/user-attachments/assets/7148bc05-b094-45b2-850a-1aab2edef14f)

ENV:
![image](https://github.com/user-attachments/assets/1210fb2c-1c76-41f9-87c0-f6d300952c75)
![image](https://github.com/user-attachments/assets/ddce3df2-191b-4d74-98c8-31c830f51dd9)

**Comment by Jooyuza** [comment]
It seems a pytorch2.3.1 issue when `vamp` over a custom `autograd.Function`, since we are using a customized backward of SVD for better numerical stability when implementing the `latent` gate.

The bug has been fixed in pytorch 2.4.0, so consider upgrade pytorch to 2.4.0 or downgrade to 2.2.2 if you want to use latent gate.

pytorch 2.4.0 +cpu:
![image](https://github.com/user-attachments/assets/a231f728-d9eb-42bb-829d-5ca91619b50f)

pytorch 2.4.0 +gpu:
![image](https://github.com/user-attachments/assets/7cf5f430-a594-4152-b3eb-0b6332d92078)

**Comment by sansiro77** [comment]
This bug was solved in https://github.com/pytorch/pytorch/pull/122902
And this PR was merged into v2.4.0, but not v2.3.1.
